export type SpanKind = 'turn' | 'flow' | 'node' | 'tool' | 'handoff' | 'llm';

export interface AgentSpan {
  traceId: string;
  spanId: string;
  parentSpanId?: string;
  name: string;
  kind: SpanKind;
  startTime: number;
  endTime?: number;
  status: 'ok' | 'error';
  events?: Array<{ name: string; time: number; attributes?: Record<string, unknown> }>;
  attributes: {
    sessionId: string;
    /** Agent active when the span opened; a turn span keeps its initiating agent across handoffs. */
    agentId?: string;
    activeFlow?: string;
    nodeId?: string;
    toolName?: string;
    handoffFrom?: string;
    handoffTo?: string;
    input?: unknown;
    output?: unknown;
    error?: string;
    /** Input tokens consumed by this turn (delta — for cost attribution). */
    tokensIn?: number;
    /** Output tokens generated by this turn (delta — for cost attribution). */
    tokensOut?: number;
    /** Context-window occupancy at this turn (last prompt tokens — a snapshot, not a delta). */
    contextTokens?: number;
    /** Prompt-cache read tokens for this turn (delta). */
    cacheReadTokens?: number;
    /** Prompt-cache write / creation tokens for this turn (delta). */
    cacheWriteTokens?: number;
  };
}

export interface AgentTrace {
  traceId: string;
  sessionId: string;
  spans: AgentSpan[];
  answer: string;
  usedTool: boolean;
  toolCalls: Array<{ name: string; args: unknown }>;
  toolResults: Array<{ name: string; result: unknown }>;
  startedAt: number;
  endedAt?: number;
}
