export type SpanKind = 'turn' | 'flow' | 'node' | 'tool' | 'handoff' | 'llm';

/** Immutable deployment identity pinned to a conversation before its first turn. */
export interface DeploymentTraceContext {
  tenantId: string;
  agentEntityId: string;
  agentVersionId: string;
  artifactDigest: string;
  releaseId: string;
  runtimeRevisionId: string;
  environment: string;
  branch?: string;
  configGeneration: number;
  secretGeneration: number;
}

export interface AgentSpan {
  traceId: string;
  spanId: string;
  parentSpanId?: string;
  name: string;
  kind: SpanKind;
  startTime: number;
  endTime?: number;
  status: 'ok' | 'error';
  events?: Array<{ name: string; time: number; attributes?: Record<string, unknown> }>;
  attributes: {
    sessionId: string;
    /** Agent active when the span opened; a turn span keeps its initiating agent across handoffs. */
    agentId?: string;
    activeFlow?: string;
    nodeId?: string;
    toolName?: string;
    handoffFrom?: string;
    handoffTo?: string;
    /** Model id on `llm` spans (`llm:${modelId}`). */
    modelId?: string;
    /** 0-based model-call index within the enclosing node loop (`llm` spans). */
    step?: number;
    input?: unknown;
    output?: unknown;
    error?: string;
    /** Input tokens consumed by this turn (delta — for cost attribution). */
    tokensIn?: number;
    /** Output tokens generated by this turn (delta — for cost attribution). */
    tokensOut?: number;
    /** Per-call input tokens on `llm` spans (sum must reconcile to turn `tokensIn`). */
    inputTokens?: number;
    /** Per-call output tokens on `llm` spans. */
    outputTokens?: number;
    /** Finish reason from the model call (`llm` spans). */
    finishReason?: string;
    /** Context-window occupancy at this turn (last prompt tokens — a snapshot, not a delta). */
    contextTokens?: number;
    /** Milliseconds from Runtime.run() trace start to the first non-empty client text delta. */
    ttftMs?: number;
    /** Prompt-cache read tokens for this turn (delta). */
    cacheReadTokens?: number;
    /** Prompt-cache write / creation tokens for this turn (delta). */
    cacheWriteTokens?: number;
    /** Out-of-node routing / decide / guard model call. */
    controlPath?: boolean;
    /** Imperative `ctx.tool` call (not model-issued). */
    imperative?: boolean;
    /** SHA-256 of the initiating agent's validated skill snapshot. */
    skillContentHash?: string;
    /** Skill snapshot hashes observed across all agents in this turn, including handoffs. */
    skillContentHashes?: Record<string, string>;
    /** Immutable publication/runtime identity. Copied to every span in the turn. */
    tenantId?: string;
    agentEntityId?: string;
    agentVersionId?: string;
    artifactDigest?: string;
    releaseId?: string;
    runtimeRevisionId?: string;
    environment?: string;
    branch?: string;
    configGeneration?: number;
    secretGeneration?: number;
  };
}

export interface AgentTrace {
  traceId: string;
  sessionId: string;
  spans: AgentSpan[];
  answer: string;
  usedTool: boolean;
  toolCalls: Array<{ name: string; args: unknown }>;
  toolResults: Array<{ name: string; result: unknown }>;
  startedAt: number;
  endedAt?: number;
}
