import type { TurnResult } from '../types/channel.js';
import type { RunContext } from '../types/run-context.js';
import { TokenAccumulator } from './TokenAccumulator.js';

export const TOKEN_USAGE_STATE_KEY = '__tokenUsage';
export const LAST_PROMPT_TOKENS_KEY = '__lastPromptTokens';
/**
 * Peak prompt size within the CURRENT user turn.
 *
 * A flow turn calls `driver.runAgentTurn` once per node, and each call builds a fresh usage
 * snapshot — so `LAST_PROMPT_TOKENS_KEY` alone records whichever node ran last. On a flow
 * turn that is typically a small extraction call, which is why a turn that sent 22,226
 * tokens reported a context of 2,166. Reset at turn open; maxed on every node.
 */
export const TURN_PEAK_PROMPT_TOKENS_KEY = '__turnPeakPromptTokens';

/** Called when a user turn opens, so the peak measures one turn and not the session. */
export function resetTurnPeakPromptTokens(state: Record<string, unknown>): void {
  delete state[TURN_PEAK_PROMPT_TOKENS_KEY];
}

export function readTurnPeakPromptTokens(state: Record<string, unknown>): number | undefined {
  const value = state[TURN_PEAK_PROMPT_TOKENS_KEY];
  return typeof value === 'number' ? value : undefined;
}

export interface PersistedTokenUsage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  cacheReadTokens?: number;
  cacheWriteTokens?: number;
}

function readPersistedUsage(state: Record<string, unknown>): PersistedTokenUsage | undefined {
  const saved = state[TOKEN_USAGE_STATE_KEY];
  if (!saved || typeof saved !== 'object') {
    return undefined;
  }
  const usage = saved as PersistedTokenUsage;
  if (
    typeof usage.inputTokens !== 'number' ||
    typeof usage.outputTokens !== 'number' ||
    typeof usage.totalTokens !== 'number'
  ) {
    return undefined;
  }
  return usage;
}

function hydrateAccumulator(state: Record<string, unknown>): TokenAccumulator {
  const acc = new TokenAccumulator();
  const saved = readPersistedUsage(state);
  if (saved) {
    acc.restoreCumulative(saved);
  }
  return acc;
}

/** Record real turn usage onto run state (survives across turns via persistence). */
export async function persistTurnUsageFromTurn(ctx: RunContext, turn: TurnResult): Promise<void> {
  if (!turn.usage) {
    return;
  }

  const acc = hydrateAccumulator(ctx.runState.state);
  const turnIndex = acc.turns.length + 1;
  acc.record({
    turn: turnIndex,
    inputTokens: turn.usage.inputTokens,
    outputTokens: turn.usage.outputTokens,
    totalTokens: turn.usage.totalTokens,
    cacheReadTokens: turn.usage.cacheReadTokens,
    cacheWriteTokens: turn.usage.cacheWriteTokens,
    latencyMs: 0,
  });

  ctx.runState.state[TOKEN_USAGE_STATE_KEY] = acc.cumulative;
  const prompt = turn.usage.contextTokens ?? turn.usage.inputTokens ?? 0;
  ctx.runState.state[LAST_PROMPT_TOKENS_KEY] = prompt;
  ctx.runState.state[TURN_PEAK_PROMPT_TOKENS_KEY] = Math.max(
    readTurnPeakPromptTokens(ctx.runState.state) ?? 0,
    prompt,
  );
  ctx.runState.updatedAt = Date.now();
  await ctx.runStore.putRunState(ctx.runState);
}

export function readLastPromptTokens(state: Record<string, unknown>): number | undefined {
  const value = state[LAST_PROMPT_TOKENS_KEY];
  return typeof value === 'number' ? value : undefined;
}

/** The session-cumulative usage persisted on run state (or undefined before any turn). */
export function readCumulativeUsage(state: Record<string, unknown>): PersistedTokenUsage | undefined {
  return readPersistedUsage(state);
}

export interface TraceTurnUsage {
  /** Input tokens consumed by THIS turn (cumulative delta since the turn opened). */
  inputTokens?: number;
  /** Output tokens generated by THIS turn (cumulative delta since the turn opened). */
  outputTokens?: number;
  /** Context-window occupancy — the last prompt's token count (not a per-turn delta). */
  contextTokens?: number;
  /** Prompt-cache read tokens for THIS turn (delta). */
  cacheReadTokens?: number;
  /** Prompt-cache write tokens for THIS turn (delta). */
  cacheWriteTokens?: number;
}

/** Per-turn token usage for a trace's `done` event. `baseline` is the cumulative
 *  usage captured when the turn OPENED, so input/output are strictly this turn's
 *  consumption (correct for cost attribution — never the running session total).
 *  `contextTokens` is the current window occupancy, which is inherently a snapshot. */
export function computeTurnTraceUsage(
  baseline: PersistedTokenUsage | undefined,
  state: Record<string, unknown>,
): TraceTurnUsage {
  // Peak across the turn's node calls, not whichever node happened to run last.
  const contextTokens = readTurnPeakPromptTokens(state) ?? readLastPromptTokens(state);
  const now = readPersistedUsage(state);
  if (!now) {
    return contextTokens === undefined ? {} : { contextTokens };
  }
  const base = baseline ?? { inputTokens: 0, outputTokens: 0, totalTokens: 0 };
  return {
    inputTokens: Math.max(0, now.inputTokens - base.inputTokens),
    outputTokens: Math.max(0, now.outputTokens - base.outputTokens),
    ...(contextTokens === undefined ? {} : { contextTokens }),
    cacheReadTokens: Math.max(0, (now.cacheReadTokens ?? 0) - (base.cacheReadTokens ?? 0)),
    cacheWriteTokens: Math.max(0, (now.cacheWriteTokens ?? 0) - (base.cacheWriteTokens ?? 0)),
  };
}
