export type {
  FileSystem,
  FsStat,
  FileSystemDirent,
  FileSystemEntryType,
  BufferEncoding,
  FileContent,
  MkdirOptions,
  RmOptions,
  CpOptions,
  ReadFileOptions,
  WriteFileOptions,
  FileEntry,
  DirectoryEntry,
  SymlinkEntry,
  LazyFileEntry,
  FsEntry,
  FileInit,
  LazyFileProvider,
  InitialFiles,
  FsError,
} from '@kuralle-agents/core';
