import type { AnyTool } from '../types/effectTool.js';
import type { FileSystem } from '../types/filesystem.js';
import type {
  SkillEntry,
  SkillLike,
  SkillMeta,
  SkillResolverContext,
  SkillSource,
  SkillStoreLike,
} from '../types/skills.js';
import { InlineSkillStore } from './inlineSkillStore.js';
import { CompositeSkillStore } from './compositeSkillStore.js';
import { fsSkillStore } from './fsSkillStore.js';
import { isPackagedSkill, isPackagedSkillArray } from './packagedSkill.js';
import { packagedSkillStore } from './packagedSkillStore.js';
import { canonicalSkillContent, sha256 } from './contentHash.js';
import { materializeSkillStore } from './materializeSkillStore.js';
import { isSkillResolver, normalizeSkillSource, substituteSkillResolvers } from './skillResolver.js';

export interface SkillWireAgent {
  /** Threaded to `SkillResolverContext.agentId` when `skills` contains a resolver. */
  id?: string;
  skills?: SkillSource;
  tools?: Record<string, AnyTool>;
  globalTools?: Record<string, AnyTool>;
  flows?: Array<{ name: string }>;
  workspace?: unknown;
}

/** Session context a `SkillResolver` entry needs, plus this session's previously resolved
 *  output (by resolver position) so a repeat call reuses it instead of re-invoking. */
export interface SkillResolverInput {
  ctx: SkillResolverContext;
  cached?: Readonly<Record<string, SkillLike[]>>;
}

export function isSkillStore(value: SkillEntry | SkillSource): value is SkillStoreLike {
  return (
    typeof value === 'object' &&
    value !== null &&
    !Array.isArray(value) &&
    'list' in value &&
    typeof (value as SkillStoreLike).list === 'function'
  );
}

async function hashSkillSnapshot(skills: readonly SkillLike[]): Promise<string> {
  const entries = await Promise.all(
    [...skills]
      .sort((a, b) => a.name.localeCompare(b.name))
      .map(async (skill) => `${skill.name}:${skill.contentHash ?? await sha256(canonicalSkillContent(skill))}`),
  );
  return sha256(entries.join('\n'));
}

export function collectRegisteredNames(agent: SkillWireAgent): Set<string> {
  const names = new Set<string>();
  for (const [key, tool] of Object.entries(agent.tools ?? {})) {
    names.add(tool.name ?? key);
  }
  for (const [key, tool] of Object.entries(agent.globalTools ?? {})) {
    names.add(tool.name ?? key);
  }
  for (const flow of agent.flows ?? []) {
    names.add(flow.name);
  }
  // Workspace tools are generated by Core rather than declared in agent.tools,
  // but skill metadata must still be able to name the capability it will use.
  if (agent.workspace) names.add('workspace');
  return names;
}

export function validateSkillAllowedTools(skills: SkillLike[], registered: Set<string>): void {
  for (const skill of skills) {
    for (const toolName of skill.allowedTools ?? []) {
      if (!registered.has(toolName)) {
        throw new Error(`skill ${skill.name}: unknown tool ${toolName}`);
      }
    }
  }
}

/**
 * Turns whatever the author wrote in `AgentConfig.skills` into one store.
 *
 * `fs` is the agent's workspace filesystem, needed only to resolve `string` entries. A path
 * without a workspace is an authoring mistake, so it throws rather than silently yielding no
 * skills — a missing skill is invisible at runtime and looks like the model ignoring it.
 */
export async function prepareSkillStore(
  source: SkillSource,
  fs?: FileSystem,
  resolver?: SkillResolverInput,
): Promise<{
  store: SkillStoreLike;
  metas: SkillMeta[];
  skills: SkillLike[];
  contentHash: string;
  /** This session's resolver output, by resolver position — present only when `source`
   *  contained a `SkillResolver`. The caller persists it so a later turn reuses it. */
  resolvedSkillsByIndex?: Record<string, SkillLike[]>;
}> {
  const normalized = normalizeSkillSource(source);

  let entries: SkillEntry[] = normalized;
  let resolvedSkillsByIndex: Record<string, SkillLike[]> | undefined;
  if (normalized.some(isSkillResolver)) {
    if (!resolver) {
      throw new Error(
        '[skills] A skill resolver requires session context. Use wireAgentSkills(), which ' +
          'supplies it, rather than calling prepareSkillStore() directly.',
      );
    }
    const substituted = await substituteSkillResolvers(normalized, resolver.ctx, resolver.cached);
    entries = substituted.entries;
    resolvedSkillsByIndex = substituted.resolvedByIndex;
  }

  // A lone store stays itself: wrapping one store in a composite would add a layer with
  // nothing to compose, and lose any extra capability the store exposes.
  if (entries.length === 1 && isSkillStore(entries[0]!)) {
    const only = entries[0] as SkillStoreLike;
    const collected = await materializeSkillStore(only);
    return {
      store: only,
      ...collected,
      contentHash: await hashSkillSnapshot(collected.skills),
      ...(resolvedSkillsByIndex ? { resolvedSkillsByIndex } : {}),
    };
  }

  const stores: SkillStoreLike[] = [];
  let inline: SkillLike[] = [];
  const flushInline = (): void => {
    if (inline.length > 0) {
      stores.push(new InlineSkillStore(inline));
      inline = [];
    }
  };

  for (const entry of entries) {
    if (typeof entry === 'string') {
      if (!fs) {
        throw new Error(
          `[skills] "${entry}" is a workspace path, but this agent has no \`workspace\` filesystem. ` +
            'Set `workspace` on the agent, or pass skills inline with defineSkill().',
        );
      }
      flushInline();
      stores.push(fsSkillStore(fs, [entry]));
      continue;
    }
    if (isSkillStore(entry)) {
      flushInline();
      stores.push(entry);
      continue;
    }
    if (isPackagedSkillArray(entry)) {
      flushInline();
      stores.push(packagedSkillStore(entry));
      continue;
    }
    if (isPackagedSkill(entry)) {
      throw new Error(
        '[skills] A packaged skill must be passed as an array entry (`skills: [[pkgA, pkgB], inlineSkill]`), not as a bare inline skill.',
      );
    }
    const inlineSkill = entry as SkillLike;
    if (inlineSkill.body === undefined) {
      throw new Error(`[skills] Inline skill "${inlineSkill.name ?? 'unknown'}" is missing a body.`);
    }
    // Consecutive inline skills share one store so ordering within a run is preserved.
    inline.push(inlineSkill);
  }
  flushInline();

  if (stores.length === 1) {
    const only = stores[0]!;
    const collected = await materializeSkillStore(only);
    return {
      store: only,
      ...collected,
      contentHash: await hashSkillSnapshot(collected.skills),
      ...(resolvedSkillsByIndex ? { resolvedSkillsByIndex } : {}),
    };
  }

  const store = new CompositeSkillStore(stores);
  const collected = await materializeSkillStore(store);
  return {
    store,
    ...collected,
    contentHash: await hashSkillSnapshot(collected.skills),
    ...(resolvedSkillsByIndex ? { resolvedSkillsByIndex } : {}),
  };
}
